Django_message/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursach.urls', namespace='cursach'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_message/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursach.urls', namespace='cursach'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursach.urls', namespace='cursach'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursach/urls.py
from django.urls import path

from cursach.apps import CursachConfig
from cursach.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, LetterListView, LetterCreateView, LetterUpdateView, LetterDeleteView, LetterDetailView, mailing_client, stats


app_name = CursachConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='cursach'),
    path('client_list/', ClientCreateView.as_view(), name='client_list'),
    path('client_form/<int:pk>/', ClientUpdateView.as_view(), name='client_form'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client_datail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('mailing_list/', MailingCreateView.as_view(), name='mailing_list'),
    path('mailing_form/<int:pk>/', MailingUpdateView.as_view(), name='mailing_form'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('letter/', LetterListView.as_view(), name='letter'),
    path('letter_list/', LetterCreateView.as_view(), name='letter_list'),
    path('letter_form/<int:pk>/', LetterUpdateView.as_view(), name='letter_form'),
    path('letter_delete/<int:pk>/', LetterDeleteView.as_view(), name='letter_delete'),
    path('letter_detail/<int:pk>/', LetterDetailView.as_view(), name='letter_detail'),
    path('mailing_client/', mailing_client, name='status'),
    path('status/', stats, name='stats')
]

cursach/models.py
from datetime import datetime, date
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=250, verbose_name='Контактная почта')
    full_name = models.CharField(max_length=250, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f'{self.full_name}, {self.email}, {self.comment}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    ONE_DAY = 'one_day'
    ONE_WEEK = 'one_week'
    ONE_MONTH = 'one_month'
    PERIODS = (
        ('one_day', 'раз в день'),
        ('one_week', "раз в неделю"),
        ('one_month', "раз в месяц")
    )
    STATUS_COMPLETED = 'completed'
    STATUS_CREATED = 'created'
    STATUS_LAUNCHED = 'launched'
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена')
    )

    client = models.ForeignKey('cursach.Client', verbose_name='Клиент', on_delete=models.SET_NULL, null=True)
    message = models.ForeignKey('cursach.Letter', verbose_name='Сообщение', on_delete=models.SET_NULL, null=True)
    time_of_mailing = models.DateTimeField(verbose_name='Время рассылки', **NULLABLE)
    periodicity = models.CharField(choices=PERIODS, default=ONE_WEEK, max_length=50,
                                   verbose_name='Периодичность')
    mailing_status = models.CharField(choices=STATUSES, default=STATUS_COMPLETED, max_length=50,
                                      verbose_name='Статус рассылки')
    start_date = models.DateTimeField(default=date.today, verbose_name='Начальная дата')
    end_date = models.DateTimeField(default=date.today, verbose_name='Конечная дата')

    def __str__(self):
        return f'{self.message}, {self.time_of_mailing}, {self.periodicity}, {self.mailing_status}, {self.start_date}, {self.end_date}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Letter(models.Model):
    letter_topic = models.CharField(max_length=350, verbose_name='Тема письма')
    letter_body = models.TextField(verbose_name='Содержимое письма')

    def __str__(self):
        return f'{self.letter_topic}, {self.letter_body}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class MailingTry(models.Model):
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки')
    answer = models.CharField(max_length=250, verbose_name='ответ сервера', **NULLABLE)

    def __str__(self):
        return f'{self.date}, {self.status}, {self.answer}'

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

cursach/views.py
import datetime
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from cursach.models import MailingTry, Client, Mailing, Letter


def stats(request):
    context = {
        'object_list': MailingTry.objects.all()
    }
    return render(request, 'cursach/stats.html', context)


class ClientListView(ListView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    fields = '__all__'
    success_url = reverse_lazy('cursach:cursach')


class ClientUpdateView(UpdateView):
    model = Client
    fields = '__all__'
    success_url = reverse_lazy('cursach:cursach')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('cursach:cursach')


class ClientDetailView(DeleteView):
    model = Client


class MailingListView(ListView):
    model = Mailing


class MailingCreateView(CreateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('cursach:mailing')


class MailingUpdateView(UpdateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('cursach:mailing')


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('cursach:mailing')


class MailingDetailView(DetailView):
    model = Mailing


class LetterListView(ListView):
    model = Letter


class LetterCreateView(CreateView):
    model = Letter
    fields = '__all__'
    success_url = reverse_lazy('cursach:letter')


class LetterUpdateView(UpdateView):
    model = Letter
    fields = '__all__'
    success_url = reverse_lazy('cursach:letter')


class LetterDeleteView(DeleteView):
    model = Letter
    success_url = reverse_lazy('cursach:letter')


class LetterDetailView(DetailView):
    model = Letter


def mailing_client(request):
    mailing_items = Mailing.objects.all()
    for item in mailing_items:
        if (
                item.mailing_status == Mailing.STATUS_CREATED or item.mailing_status == Mailing.STATUS_LAUNCHED) and item.start_date == datetime.date.today() and item.end_date >= datetime.date.today() and item.time_of_mailing >= datetime.datetime.now().time():
            item.mailing_status = Mailing.STATUS_LAUNCHED
            item.save()
            try:
                result = send_mail(
                    subject=item.message.letter_topic,
                    message=item.message.letter_body,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[item.client.email],
                    fail_silently=False
                )
                if result:
                    item.mailing_status = Mailing.STATUS_COMPLETED
                    item.save()
                MailingTry.objects.create(
                    status=item.mailing_status,
                    answer=200
                )
            except Exception as e:
                MailingTry.objects.create(
                    status=item.mailing_status,
                    answer=e
                )
    return redirect(reverse('cursach:mailing'))

cursach/templates/cursach/Mailing_delete.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'cursach:cursach' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/Mailing_detail.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Клиент</td>
                            <td>{{ object.client.email }}</td>
                        </tr>
                        <tr>
                            <td>Начальная дата</td>
                            <td>{{ object.start_date }}</td>
                        </tr>
                        <tr>
                            <td>Конечная дата</td>
                            <td>{{ object.end_date }}</td>
                        </tr>
                        <tr>
                            <td>Время отправки</td>
                            <td>{{ object.time_of_mailing }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность</td>
                            <td>{{ object.periodicity }}</td>
                        </tr>
                        <tr>
                            <td>Статус рассылки</td>
                            <td>{{ object.mailing_status }}</td>
                        </tr>
                        <tr>
                            <td>Тема письма</td>
                            <td>{{ object.message.letter_topic }}</td>
                        </tr>
                        <tr>
                            <td>Содержание письма</td>
                            <td>{{ object.message.letter_body }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/Mailing_form.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/Mailing_list.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-info" href="{% url 'cursach:mailing_list' %}">Создать рассылку</a>
            <a class="btn btn-info" href="{% url 'cursach:stats' %}">Статус отправки</a>
        </nav>
    </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Клиент</th>
                <th scope="col">Начальная дата</th>
                <th scope="col">Конечная дата</th>
                <th scope="col">Время рассылки</th>
                <th scope="col">Периодичность</th>
                <th scope="col">Статус рассылки</th>
                <th scope="col">Тема письма</th>
                <th scope="col">Содержание письма</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'cursach:letter_detail' object.pk %}">
                            #{{ object.pk }}
                        </a>
                    </td>
                    <td>{{ object.letter_topic }}</td>
                    <td>{{ object.letter_body }}</td>
                    <td>
                        <a class="btn btn-info" href="{% url 'cursach:mailing_detail' object.pk %}">
                            #{{ object.pk }}
                        </a>
                    </td>
                    <td>{{ object.client.email }}</td>
                    <td>{{ object.start_date }}</td>
                    <td>{{ object.end_date }}</td>
                    <td>{{ object.time_of_mailing }}</td>
                    <td>{{ object.periodicity }}</td>
                    <td>{{ object.mailing_status }}</td>
                    <td>{{ object.message.letter_topic }}</td>
                    <td>{{ object.message.letter_body }}</td>
                    <td>
                        <a class="btn btn-info" href="{% url 'cursach:mailing_form' object.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cursach:mailing_delete' object.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

cursach/templates/cursach/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сервис управления рассылками</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl603oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{%  include 'cursach/includes/my_menu.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

cursach/templates/cursach/client_delete.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'cursach:cursach' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/client_detail.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Контактная почта</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        <tr>
                            <td>ФИО</td>
                            <td>{{ object.full_name }}</td>
                        </tr>
                        <tr>
                            <td>Комментарии</td>
                            <td>{{ object.comment }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/client_form.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/client_list.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-info" href="{% url 'cursach:client_list' %}">Создать клиента</a>
        </nav>
    </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Контактная почта</th>
                <th scope="col">ФИО</th>
                <th scope="col">Комментарий</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'cursach:client_detail' object.pk %}">
                            #{{ object.pk }}
                        </a>
                    </td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.full_name }}</td>
                    <td>{{ object.comment }}</td>
                    <td>
                        <a class="btn btn-info" href="{% url 'cursach:client_form' object.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cursach:client_delete' object.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

cursach/templates/cursach/letter_delete.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'cursach:cursach' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/letter_detail.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Тема письма</td>
                            <td>{{ object.letter_topic }}</td>
                        </tr>
                        <tr>
                            <td>Содержание письма</td>
                            <td>{{ object.full_name }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/letter_form.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cursach/templates/cursach/letter_list.html
{% extends 'cursach/base.html' %}

{% block content %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-info" href="{% url 'cursach:letter_list' %}">Создать письмо</a>
        </nav>
    </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Тема письма</th>
                <th scope="col">Содержание письма</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'cursach:letter_detail' object.pk %}">
                            #{{ object.pk }}
                        </a>
                    </td>
                    <td>{{ object.letter_topic }}</td>
                    <td>{{ object.letter_body }}</td>
                    <td>
                        <a class="btn btn-info" href="{% url 'cursach:letter_form' object.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cursach:letter_delete' object.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

cursach/templates/cursach/stats.html
{% extends 'cursach/base.html' %}

{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primary border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис</h5>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата и время попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td> {{ object.id }}</td>
                <td> {{ object.date }}</td>
                <td> {{ object.status }}</td>
                <td> {{ object.answer }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}